### ISSUE TITLE
Lots of YouTube videos on your blacklist

### ISSUE THREAD

**Issue by Perflyst** [smokingwheels/smokingwheels.github.io#1]
I am using your Allhosts list and have problems with Youtube videos. I searched your list and found many *. googlevideo. com URLs. 

Why do you block them? Can you please remove them?

**Comment by smokingwheels** [comment]
Is is possible to whitelist them?
It can be your geo location that effects it.

**Comment by Nivl** [comment]
Same issue here (I'm in the US). I've been whitelisting them but it's becoming a pain to do so, I'm already at 35 (added manually when a video refuses to play) and I don't really feel like adding the other 18k to the whitelist (even programmatically). It would be nice if the youtube links were part of a different list since they don't work for everyone (or have another list without them?).

**Comment by smokingwheels** [comment]
You are welcome to copy and edit the list.
Then you need to host it somewhere.

https://manage.dediserve.com/?affid=1144

2 smokingwheels
https://vault.dediserve.com/s/4sqKKMPkEFXsgzy/download

3 attack
https://vault.dediserve.com/s/noCYxiqNaXErGWW/download

4 allhosts
https://vault.dediserve.com/s/QGW9QpfS3S9ykHK/download

5 w10
https://vault.dediserve.com/s/cCiECgWPiQdE9KP/download

6 manualblock.txt
https://vault.dediserve.com/s/cw5ArtRQHoWa5QK/download

7 manualwhitelist.txt
https://vault.dediserve.com/s/EwY2qaHPLxcKsYk/download

8
